<a href="https://colab.research.google.com/github/Mark-med/CHM/blob/main/lb4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Медведчук Марк 13 варіант лаба 4

In [1]:
import numpy as np
a_arr = np.array([[2, 3, 1], [-1, 1, 0], [1, 2, -1]])
b_arr = np.array([[1, 2, 1], [0, 1, 2], [3, 1, 1]])
c = b_arr.dot(a_arr) + a_arr.dot(b_arr)

print(c)

[[ 6 15  9]
 [ 0  4 -1]
 [ 4 15  6]]


In [2]:
import numpy as np
arr = np.array([[-1, 2], [0, 1],])
power= np.dot(arr,arr)
print(power)

[[1 0]
 [0 1]]


In [3]:
import numpy as np
matrix_1 = np.array([[5, 8 , -4], [6 , 9 , -5], [4, 7, -3]])
matrix_2 = np.array([[3, 2, 5], [4, -1,3] , [9 ,6 ,5]])
matrix_3 = matrix_1.dot(matrix_2)
print(matrix_3)


[[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


In [4]:
import numpy as np
arr_a = np.array([[2, 4, 5], [1, 1, 2], [2, 4, 3]])
a_det = np.linalg.det(arr_a)
print(format(a_det,'.9g'))

4


In [5]:
import numpy as np
a_arr = np.array([[1, 2, 0,0,0], [1, 0, 2, 0,0], [1, 0, 0, 2,0], [1, 0, 0, 0,2],[0,0,1,1,1]])
a_det = np.linalg.det(a_arr)
print(format(a_det,'.9g'))

-24


In [6]:
a = np.array([[1, 2, 2], [2, 1, -2], [2, -2, 1]])
a_inv = np.linalg.inv(a)
print(a_inv)


[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


In [7]:
aa = np.array([[1, 2, 3,4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
rank = np.linalg.matrix_rank(aa)
print(rank)


2


In [9]:
A = np.matrix('1 -4 0; 2 -3 1; 1 4 2')
B = np.matrix('-5; -7; -1')
print('A=', A)
print('B=',B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print('X=',X)

A= [[ 1 -4  0]
 [ 2 -3  1]
 [ 1  4  2]]
B= [[-5]
 [-7]
 [-1]]
[[-5.   4.  -2. ]
 [-1.5  1.  -0.5]
 [ 5.5 -4.   2.5]]
X= [[-1.]
 [ 1.]
 [-2.]]


In [10]:
import numpy as np

a = np.matrix('1 -4 0; 2 -3 1; 1 4 2')
b = np.matrix('-5; -7; -1')
def kram(a,b):
    det_a = np.linalg.det(a)
    if det_a != 0:
       a1 = np.matrix(a)
       a2 = np.matrix(a)
       a3 = np.matrix(a)
       a1[:, 0] = b
       a2[:, 1] = b
       a3[:, 2] = b
       x = np.linalg.det(a1)/det_a
       y =np.linalg.det(a2)/det_a
       z= np.linalg.det(a3)/det_a
       print('Solving a system of linear algebraic equations by Cramer*s method')
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3))
    else:
        print('Determinant equals zero, the system has no solutions')
    return x,y,z
kram(a,b)
print('Checking the correctness of the solution\n', np.linalg.solve(a,b).round(3))

Solving a system of linear algebraic equations by Cramer*s method
x= -1.0 y= 1.0 z= -2.0
Checking the correctness of the solution
 [[-1.]
 [ 1.]
 [-2.]]


In [12]:
import numpy as np

a = np.array(np.random.randint(0, 5, size=(5, 3)))

average_rows = np.mean(a, axis=1)
average_columns = np.mean(a, axis=0)
minimum_average_row = np.min(average_rows)

print(a)
print(f"Середні значення рядків: {average_rows}")
print(f"Середні значення стовпців: {average_columns}")
print(f"Найнижче середнє значення серед рядків: {minimum_average_row}")

[[1 1 1]
 [4 2 1]
 [0 2 3]
 [2 1 0]
 [1 4 0]]
Середні значення рядків: [1.         2.33333333 1.66666667 1.         1.66666667]
Середні значення стовпців: [1.6 2.  1. ]
Найнижче середнє значення серед рядків: 1.0
